(()=>{let products=[],byKey=new Map(),lastFocus=null;const norm=s=>String(s||'').toUpperCase().replace(/[^A-Z0-9]+/g,' ').trim();const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function index(data){products=data.products||[];for(const p of products){byKey.set(p.product_id,p);[p.name,p.official_ncabc_name,...(p.aliases||[])].filter(Boolean).forEach(x=>byKey.set(norm(x),p));}}
function modal(){let m=document.getElementById('aimProductModal');if(m)return m;document.body.insertAdjacentHTML('beforeend',`<div class="aim-modal" id="aimProductModal" hidden><div class="aim-modal-backdrop" data-aim-close></div><section class="aim-modal-dialog" role="dialog" aria-modal="true" aria-labelledby="aimProductTitle"><button class="aim-modal-close" data-aim-close aria-label="Close">×</button><div id="aimProductContent"></div></section></div>`);m=document.getElementById('aimProductModal');m.addEventListener('click',e=>{if(e.target.closest('[data-aim-close]'))close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!m.hidden)close()});return m}
function val(x,fallback='Not currently listed'){return x!==null&&x!==undefined&&String(x).trim()?esc(x):fallback}function price(x){return typeof x==='number'?`$${x.toFixed(2)}`:'Not currently listed'}
function open(key,push=true){const p=byKey.get(key)||byKey.get(norm(key));const m=modal(),c=document.getElementById('aimProductContent');lastFocus=document.activeElement;m.hidden=false;document.body.style.overflow='hidden';if(!p){c.innerHTML='<div class="aim-product-error">Product details are not currently available.</div>';return}c.innerHTML=`<div class="aim-modal-head"><h2 id="aimProductTitle">${esc(p.name)}</h2><span class="aim-tracked">Tracked by AIM ✓</span></div><div class="aim-modal-body">${p.official_ncabc_name&&norm(p.official_ncabc_name)!==norm(p.name)?`<p class="aim-official-name">Official NCABC listing: ${esc(p.official_ncabc_name)}</p>`:''}<div class="aim-detail-grid"><div class="aim-detail"><span>NC ABC Price</span><b>${price(p.nc_abc_price)}</b></div><div class="aim-detail"><span>Proof</span><b>${val(p.proof)}</b></div><div class="aim-detail"><span>Bottle Size</span><b>${val(p.bottle_size)}</b></div><div class="aim-detail"><span>Classification</span><b>${val(p.classification,'Not listed on current official list')}</b></div><div class="aim-detail"><span>Supplier</span><b>${val(p.supplier)}</b></div></div><p class="aim-modal-note">Official product data is sourced from NCABC records and AIM’s canonical Product Master.</p></div>`;if(push){const u=new URL(location.href);u.searchParams.set('product',p.product_id);history.pushState({product:p.product_id},'',u)}m.querySelector('.aim-modal-close').focus()}
function close(push=true){const m=modal();m.hidden=true;document.body.style.overflow='';if(push){const u=new URL(location.href);u.searchParams.delete('product');history.pushState({},'',u)}if(lastFocus)lastFocus.focus()}
function linkify(root=document){root.querySelectorAll('[data-product-name]').forEach(el=>{const p=byKey.get(norm(el.dataset.productName));if(!p)return;el.classList.add('aim-product-link');el.setAttribute('href',`?product=${encodeURIComponent(p.product_id)}`);el.dataset.productId=p.product_id})}
document.addEventListener('click',e=>{const a=e.target.closest('.aim-product-link');if(!a)return;e.preventDefault();open(a.dataset.productId||a.dataset.productName)});window.addEventListener('popstate',()=>{const k=new URLSearchParams(location.search).get('product');k?open(k,false):close(false)});
window.AIMProducts={ready:fetch('public_aim_products.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('Product feed unavailable');return r.json()}).then(d=>{index(d);linkify();const k=new URLSearchParams(location.search).get('product');if(k)open(k,false);return products}),linkify,open,getAll:()=>products};})();
